GET http://localhost/socialproject2025/api/users.php
Content-Type: application/json

###
POST http://localhost/socialproject2025/api/users.php
Content-Type: application/json

###
PUT http://localhost/socialproject2025/api/users.php
Content-Type: application/json

###
DELETE http://localhost/socialproject2025/api/users.php
Content-Type: application/json
